### ISSUE TITLE
Crash when loading game with mod installed.

### ISSUE THREAD

**Issue by theDaleighChronicle** [squeek502/SpiceOfLife#158]
Below is my crash report and what the launcher also said upon crash. I am using Minecraft version 1.12.2 and forge 14.23.5.2780
I do have it in a pack, but the launcher specified it was an issue with The Spice of Life.

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from The Spice of Life (spiceoflife)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.5-139.jar)
  LoadingPlugin (HardcoreBuoy-1.12-1.0.4.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  CoreModMain (lda-0.1.6-corePlugin.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
  CorePlugin (UnicodeFontExtension-1.12.2-2.7.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.4.10.6.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.145.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  SmoothWaterCore (SmoothWater-0.1.4.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 1/10/19 10:46 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from The Spice of Life (spiceoflife)
Caused by: java.lang.NoClassDefFoundError: hb
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at squeek.spiceoflife.network.simpleimpl.BetterSimpleChannelHandlerWrapper.<clinit>(BetterSimpleChannelHandlerWrapper.java:48)
	at squeek.spiceoflife.network.simpleimpl.BetterSimpleNetworkWrapper.getHandlerWrapper(BetterSimpleNetworkWrapper.java:71)
	at squeek.spiceoflife.network.simpleimpl.BetterSimpleNetworkWrapper.addClientHandlerAfter(BetterSimpleNetworkWrapper.java:65)
	at squeek.spiceoflife.network.simpleimpl.BetterSimpleNetworkWrapper.registerMessage(BetterSimpleNetworkWrapper.java:53)
	at squeek.spiceoflife.network.PacketHandler$PacketType.<init>(PacketHandler.java:32)
	at squeek.spiceoflife.network.PacketHandler$PacketType.<init>(PacketHandler.java:26)
	at squeek.spiceoflife.network.PacketHandler$PacketType.<clinit>(PacketHandler.java:16)
	at squeek.spiceoflife.ModSpiceOfLife.init(ModSpiceOfLife.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 866462536 bytes (826 MB) / 3671064576 bytes (3501 MB) up to 7923040256 bytes (7556 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8500m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2780 Optifine OptiFine_1.12.2_HD_U_E2 100 mods loaded, 100 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version              | Source                                        | Signature                                |
	|:----- |:------------------------ |:-------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft                | 1.12.2               | minecraft.jar                                 | None                                     |
	| LCHI  | mcp                      | 9.42                 | minecraft.jar                                 | None                                     |
	| LCHI  | FML                      | 8.0.99.99            | forge-1.12.2-14.23.5.2780.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge                    | 14.23.5.2780         | forge-1.12.2-14.23.5.2780.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | unicodefontextensioncore | 1.12.2-2.6           | minecraft.jar                                 | None                                     |
	| LCHI  | obfuscate                | 0.2.6                | minecraft.jar                                 | None                                     |
	| LCHI  | dsurroundcore            |                      | minecraft.jar                                 | None                                     |
	| LCHI  | unicodefontextension     | 1.12.2-2.7           | UnicodeFontExtension-1.12.2-2.7.jar           | None                                     |
	| LCHI  | biomesoplenty            | 7.0.1.2424           | BiomesOPlenty-1.12.2-7.0.1.2424-universal.jar | None                                     |
	| LCHI  | craftstudioapi           | 1.0.0                | CraftStudio-1.0.0.93-mc1.12-alpha.jar         | None                                     |
	| LCHI  | harvestcraft             | 1.12.2zb             | Pam's HarvestCraft 1.12.2zb.jar               | None                                     |
	| LCHI  | animania                 | 1.6.2                | animania-1.12.2-1.6.2.jar                     | None                                     |
	| LCHI  | antiqueatlas             | 4.4.9                | antiqueatlas-1.12.2-4.4.9.jar                 | None                                     |
	| LCHI  | antiqueatlasoverlay      | 1.2                  | antiqueatlas-1.12.2-4.4.9.jar                 | None                                     |
	| LCHI  | examplemod               | 1.0                  | antiqueatlas-1.12.2-4.4.9.jar                 | None                                     |
	| LCHI  | applecore                | 3.1.4                | AppleCore-mc1.12.2-3.1.4.jar                  | None                                     |
	| LCHI  | aquaculture              | 1.6.7                | Aquaculture-1.12.2-1.6.7.jar                  | None                                     |
	| LCHI  | architecturecraft        | @VERSION@            | architecturecraft-1.12-3.80.jar               | None                                     |
	| LCHI  | crafttweaker             | 4.1.13               | CraftTweaker2-1.12-4.1.13.jar                 | None                                     |
	| LCHI  | mantle                   | 1.12-1.3.3.39        | Mantle-1.12-1.3.3.39.jar                      | None                                     |
	| LCHI  | jei                      | 4.14.3.248           | jei_1.12.2-4.14.3.248.jar                     | None                                     |
	| LCHI  | tconstruct               | 1.12.2-2.12.0.113    | TConstruct-1.12.2-2.12.0.113.jar              | None                                     |
	| LCHI  | conarm                   | 1.2.2                | conarm-1.12.2-1.2.2.jar                       | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHI  | moartinkers              | 0.6.0                | moartinkers-0.6.0.jar                         | None                                     |
	| LCHI  | baubles                  | 1.5.2                | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHI  | plustic                  | 7.0.0.0              | plustic-7.0.0.0.jar                           | None                                     |
	| LCHI  | armoryexpansion          | 0.2.0                | armoryexpansion-0.2.0.jar                     | None                                     |
	| LCHI  | quark                    | r1.5-139             | Quark-r1.5-139.jar                            | None                                     |
	| LCHI  | autoreglib               | 1.3-24               | AutoRegLib-1.3-24.jar                         | None                                     |
	| LCHI  | auto_third_person        | 1.2.0                | autothirdperson-1.2.0.jar                     | None                                     |
	| LCHI  | bamboozled               | 1.1.0                | Bamboozled-1.12-1.1.0.jar                     | None                                     |
	| LCHI  | baubleofundying          | 1.0.1                | BaubleOfUndying-1.12-1.0.1.jar                | None                                     |
	| LCHI  | bhc                      | 1.2.1                | baubley-heart-canisters-1.12.2-1.2.1.jar      | None                                     |
	| LCHI  | betterbedrockgen         | 6.0.2                | BetterBedrockGenerator-1.12-6.1.1.jar         | None                                     |
	| LCHI  | forgelin                 | 1.8.2                | Forgelin-1.8.2.jar                            | None                                     |
	| LCHI  | betterfoliage            | 2.2.0                | BetterFoliage-MC1.12-2.2.0.jar                | None                                     |
	| LCHI  | betterquesting           | 3.5.284              | BetterQuesting-3.5.284.jar                    | None                                     |
	| LCHI  | bqt                      | 1.0                  | BetterQuestingTriggerer-1.0.jar               | None                                     |
	| LCHI  | bibliocraft              | 2.4.5                | BiblioCraft[v2.4.5][MC1.12.2].jar             | None                                     |
	| LCHI  | blockdrops               | 1.4.0                | blockdrops-1.12.2-1.4.0.jar                   | None                                     |
	| LCHI  | carryon                  | 1.12.1               | CarryOn MC1.12.2 v1.12.1.jar                  | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHI  | cdm                      | 0.4.1                | cdm-0.4.1-mc1.12.2.jar                        | None                                     |
	| LCHI  | chiselsandbits           | 14.29                | chiselsandbits-14.29.jar                      | None                                     |
	| LCHI  | morpheus                 | 1.12-3.3.2           | Morpheus-1.12-3.3.2.jar                       | None                                     |
	| LCHI  | comforts                 | 1.4.1.1              | comforts-1.12.2-1.4.1.1.jar                   | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHI  | controlling              | 3.0.6                | Controlling-3.0.6.jar                         | None                                     |
	| LCHI  | cookingforblockheads     | 6.4.65               | CookingForBlockheads_1.12.2-6.4.65.jar        | None                                     |
	| LCHI  | ctgui                    | 1.0.0                | CraftTweaker2-1.12-4.1.13.jar                 | None                                     |
	| LCHI  | crafttweakerjei          | 2.0.2                | CraftTweaker2-1.12-4.1.13.jar                 | None                                     |
	| LCHI  | customnpcs               | 1.12                 | CustomNPCs_1.12.2(26aug18).jar                | None                                     |
	| LCHI  | debarkedlogs             | ${version}           | Debarked Logs-1.0.5-1.12.jar                  | None                                     |
	| LCHI  | dirt2path                | 1.7.1                | dirt2path-1.8.0.jar                           | None                                     |
	| LCHI  | lootablebodies           | 2.4.0                | DrCyanosLootableBodies_1.12-2.4.0.jar         | None                                     |
	| LCHI  | fairylights              | 2.1.5                | fairylights-2.1.5-1.12.2.jar                  | None                                     |
	| LCHI  | familiarfauna            | 1.0.11               | FamiliarFauna-1.12.2-1.0.11.jar               | None                                     |
	| LCHI  | fenceoverhaul            | 1.3.4                | FenceOverhaul-1.3.4.jar                       | None                                     |
	| LCHI  | ferdinandsflowers        | 1.10.4.1             | Ferdinand's Flowers-1.12.x-1.10.4.1.jar       | None                                     |
	| LCHI  | cfm                      | 6.2.0                | furniture-6.2.0-1.12.2.jar                    | None                                     |
	| LCHI  | hardcorebuoy             | ${version}           | HardcoreBuoy-1.12-1.0.4.jar                   | None                                     |
	| LCHI  | harvest                  | 1.12-1.2.7-20        | Harvest-1.12-1.2.7-20.jar                     | None                                     |
	| LCHI  | inventorytweaks          | 1.64+dev.145.16d98f2 | InventoryTweaks-1.64+dev.145.jar              | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHI  | jehc                     | 1.12.2               | JEHC-1.12.2-1.6.2.0.jar                       | None                                     |
	| LCHI  | jeiintegration           | 1.5.1.36             | jeiintegration_1.12.2-1.5.1.36.jar            | None                                     |
	| LCHI  | jarm                     | 1.1.2                | Just A Raft Mod-1.1.2.jar                     | None                                     |
	| LCHI  | jeresources              | 0.8.10.50            | JustEnoughResources-1.12.2-0.8.10.50.jar      | None                                     |
	| LCHI  | lootchests               | 1.2.2                | lootchests-1.2.2.jar                          | None                                     |
	| LCHI  | malisiscore              | 1.12.2-6.4.0         | malisiscore-1.12.2-6.4.0.jar                  | None                                     |
	| LCHI  | malisisdoors             | 1.12.2-7.3.0         | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| LCHI  | radixcore                | 1.12.x-2.2.1         | RadixCore-1.12.x-2.2.1-universal.jar          | None                                     |
	| LCHI  | mca                      | 1.12.2-5.3.1         | MCA-1.12.x-5.3.1-universal.jar                | None                                     |
	| LCHI  | mcjtylib_ng              | 3.0.7                | mcjtylib-1.12-3.0.7.jar                       | None                                     |
	| LCHI  | mtrm                     | 1.2.2.30             | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar    | None                                     |
	| LCHI  | moreplayermodels         | 1.12.2               | MorePlayerModels_1.12.2(18jan18).jar          | None                                     |
	| LCHI  | notenoughwands           | 1.7.1                | notenoughwands-1.12-1.7.1.jar                 | None                                     |
	| LCHI  | bq_npc_integration       | 3.4.26               | NPCIntegration-3.4.26.jar                     | None                                     |
	| LCHI  | omca                     | 2.0.0                | omca-1.12.2-2.0.0.jar                         | None                                     |
	| LCHI  | oredicttips              | 2.0.2                | OreDictTips-1.12-2.0.2.jar                    | None                                     |
	| LCHI  | getalltheseeds           | 1.12a                | Pam's Get all the Seeds! 1.12a.jar            | None                                     |
	| LCHI  | pamsimpleharvest         | 2.0.0                | pamsimpleharvest-2.0.0.jar                    | None                                     |
	| LCHI  | prettybeaches            | 1.0.4                | PrettyBeaches_1.12.2-1.0.4.jar                | None                                     |
	| LCHI  | quickleafdecay           | 1.2.4                | QuickLeafDecay-MC1.12.1-1.2.4.jar             | None                                     |
	| LCHI  | realdrops                | 1.2.14               | RealisticItemDrops-1.2.14.jar                 | None                                     |
	| LCHI  | schematics               | 1.12.2.12            | Schematics-1.12.2.12.jar                      | None                                     |
	| LCHI  | sereneseasons            | 1.2.15               | SereneSeasons-1.12.2-1.2.15-universal.jar     | None                                     |
	| LCHI  | signpost                 | 1.07.2               | signpost-1.12-1.07.2.jar                      | None                                     |
	| LCHI  | smoothwater              | 0.1.4                | SmoothWater-0.1.4.jar                         | None                                     |
	| LCHI  | soundfilters             | 0.10_for_1.12        | SoundFilters-0.10_for_1.12.jar                | None                                     |
	| LCHE  | spiceoflife              | 1.3.12               | SpiceOfLife-mc1.12-1.3.12.jar                 | None                                     |
	| LCH   | bq_standard              | @VERSION@            | StandardExpansion-3.4.148.jar                 | None                                     |
	| LCH   | tails                    | 1.12-1.10.0          | Tails-1.12-1.10.0.jar                         | None                                     |
	| LCH   | tallgates                | 1.0.0                | TallGates-1.12.2-1.0.0.1.jar                  | None                                     |
	| LCH   | theoneprobe              | 1.4.25               | theoneprobe-1.12-1.4.25.jar                   | None                                     |
	| LCH   | tinkersjei               | 1.0                  | tinkersjei-1.0.jar                            | None                                     |
	| LCH   | variedcommodities        | 1.12.2               | VariedCommodities_1.12.2(15may18.jar          | None                                     |
	| LCH   | vehicle                  | 0.35.0               | vehicle-mod-0.35.0-1.12.2.jar                 | None                                     |
	| LCH   | wearablebackpacks        | 3.1.3                | WearableBackpacks-1.12.2-3.1.3.jar            | None                                     |
	| LCH   | dsurround                | 3.4.10.6             | DynamicSurroundings-1.12.2-3.4.10.6.jar       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | presets                  | 3.4.10.6             | DynamicSurroundings-1.12.2-3.4.10.6.jar       | None                                     |
	| LCH   | lda                      | 0.1.6                | lda-0.1.6.jar                                 | None                                     |
	| LCH   | orelib                   | 3.5.2.1              | OreLib-1.12.2-3.5.2.1BETA.jar                 | 7a2128d395ad96ceb9d9030fbd41d035b435753a |

	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.5-139.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (HardcoreBuoy-1.12-1.0.4.jar)
  betterwithmods.core.ClassTransformer
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CoreModMain (lda-0.1.6-corePlugin.jar)
  io.github.lukas2005.DeviceModApps.coremod.ClassTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
CorePlugin (UnicodeFontExtension-1.12.2-2.7.jar)
  bre.ufex.asm.Transformer
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.4.10.6.jar)
  org.blockartistry.DynSurround.asm.Transformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.145.jar)
  invtweaks.forge.asm.ContainerTransformer
AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  squeek.applecore.asm.TransformerModuleHandler
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
SmoothWaterCore (SmoothWater-0.1.4.jar)
  pl.asie.smoothwater.SmoothWaterTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 417.35' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.17 High.zip
	OpenGlVersion: 4.6.0 NVIDIA 417.35
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by squeek502** [comment]
Try removing The Spice of Life and see if it still crashes.

**Comment by theDaleighChronicle** [comment]
I removed the mod, and the game worked fine.

**Comment by squeek502** [comment]
Okay, thanks. Not sure what could be causing it, will look into it more when I get a chance.
