### ISSUE TITLE
(1.6.4) (1.1.0) Internal Server Error when eating Mariculture's (1.2.2f) Raw Squid (SMP Only)

### ISSUE THREAD

**Issue by Geijoh** [squeek502/SpiceOfLife#16]
With the following error:

[ForgeModLoader] A critical server error occured handling a packet, kicking 516753
net.minecraft.util.ReportedException: Ticking player
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:488)
    at net.minecraft.network.NetServerHandler.func_72498_a(NetServerHandler.java:511)
    at net.minecraft.network.packet.Packet10Flying.func_73279_a(SourceFile:136)
    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:476)
    at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:234)
    at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
    at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(DedicatedServerListenThread.java:37)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:917)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:331)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:666)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class squeek.spiceoflife.proxy.ProxyMariculture
    at squeek.spiceoflife.helpers.FoodHelper.isFood(FoodHelper.java:23)
    at squeek.spiceoflife.asm.Hooks.onFoodEaten(Hooks.java:89)
    at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:309)
    at net.minecraft.entity.player.EntityPlayer.func_71036_o(EntityPlayer.java:530)
    at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerMP.java:1232)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:325)
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:423)
    ... 11 moress squeek.spiceoflife.proxy.ProxyMariculture

**Comment by squeek502** [comment]
Could I get the full server log?

**Comment by Geijoh** [comment]
Here is the full error from the server log. If you're wanting the WHOLE server log, I can do so.

http://pastebin.com/7rJB2zx4

**Comment by squeek502** [comment]
Thanks, that's what I needed. Will look into it soon.
