### ISSUE TITLE
Fatal startup crash

### ISSUE THREAD

**Issue by ghost** [squeek502/SpiceOfLife#19]
Using:
SpiceOfLife-mc1.6.4-1.1.1
forge-1.7.10-10.13.0.1207-universal

```
[12:08:49] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[12:08:49] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[12:08:49] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[12:08:49] [main/INFO] [FML]: Forge Mod Loader version 7.10.25.1207 for Minecraft 1.7.10 loading
[12:08:49] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.7.0_40, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre7
[12:08:49] [main/WARN] [FML]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:08:49] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
Warning: version of ForgeMultipart, 1.1.0.300 is newer than request 1.1.0.297
[12:08:49] [main/WARN] [FML]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:08:49] [main/WARN] [FML]: The coremod com.rebelkeithy.dualhotbar.DualHotbarPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:08:49] [main/WARN] [FML]: The coremod fastcraft.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:08:49] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:08:49] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:08:49] [main/WARN] [FML]: The coremod mekanism.common.asm.LoadingHook does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:08:49] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:08:49] [main/WARN] [FML]: The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:08:50] [main/WARN] [FML]: The coremod openmods.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:08:50] [main/WARN] [FML]: The coremod lumien.randomthings.Transformer.RTLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:08:50] [main/WARN] [FML]: The coremod com.dynious.refinedrelocation.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:08:50] [main/WARN] [FML]: The coremod tonius.simplyjetpacks.core.SJCoreContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[12:08:50] [main/WARN] [FML]: The coremod squeek.spiceoflife.asm.ASMPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
java.lang.AbstractMethodError
at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:423)
at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:310)
at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:211)
at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:421)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:512)
at org.multimc.EntryPoint.listen(EntryPoint.java:165)
at org.multimc.EntryPoint.main(EntryPoint.java:54)
[12:08:50] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at S:\minecraft\instances\uranium\minecraft for Forge Mod Loader
java.lang.AbstractMethodError
at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:423) ~[forge-1.7.10-10.13.0.1207-universal.jar:?]
at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:310) ~[forge-1.7.10-10.13.0.1207-universal.jar:?]
at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:211) ~[forge-1.7.10-10.13.0.1207-universal.jar:?]
at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.0.1207-universal.jar:?]
at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.0.1207-universal.jar:?]
at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.0.1207-universal.jar:?]
at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.0.1207-universal.jar:?]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:114) [launchwrapper-1.9.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_40]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_40]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_40]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_40]
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:421) [NewLaunch.jar:?]
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:512) [NewLaunch.jar:?]
at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Exiting with -1
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:421)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:512)
at org.multimc.EntryPoint.listen(EntryPoint.java:165)
at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.AbstractMethodError
at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:423)
at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:310)
at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:211)
at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
... 8 more
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 5
at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
at java.lang.SecurityManager.checkExit(Unknown Source)
at java.lang.Runtime.exit(Unknown Source)
at java.lang.System.exit(Unknown Source)
at org.multimc.EntryPoint.main(EntryPoint.java:58)
Minecraft exited with exitcode 1.
```

**Comment by squeek502** [comment]
You're trying to use the 1.6.4 version in 1.7.10.
