### ISSUE TITLE
Drinking water bottles causes internal exception with envriomine on server.

### ISSUE THREAD

**Issue by aziel13** [squeek502/SpiceOfLife#24]
When drinking water bottles on my private server a player will get an end of stream.This seems to be related to the closed issue for enviormine when drinking the water bottles.
[GitHub](https://github.com/Funwayguy/EnviroMine/issues/35)

My server log seems to indicate its an issue related to spice of life so I thought it best to bring it up here as well.

The server log related to this is as follows: 
2014-08-28 15:31:27 [WARNING] Failed to handle packet for aziel13/98.115.14.29: net.minecraft.util.ReportedException: Ticking player
net.minecraft.util.ReportedException: Ticking player
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:488)
at net.minecraft.network.NetServerHandler.func_72498_a(NetServerHandler.java:511)
at net.minecraft.network.packet.Packet10Flying.func_73279_a(SourceFile:136)
at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:480)
at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:234)
at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(DedicatedServerListenThread.java:37)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:917)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:331)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:666)
at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class squeek.spiceoflife.proxy.ProxyMariculture
at squeek.spiceoflife.helpers.FoodHelper.isFood(FoodHelper.java:23)
at squeek.spiceoflife.asm.Hooks.onFoodEaten(Hooks.java:89)
at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:309)
at net.minecraft.entity.player.EntityPlayer.func_71036_o(EntityPlayer.java:530)
at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerMP.java:1215)
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:325)
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:423)
... 11 more

**Comment by squeek502** [comment]
Should be fixed in v1.1.1. See #16
