### ISSUE TITLE
Render crash with food journal.

### ISSUE THREAD

**Issue by ghost** [squeek502/SpiceOfLife#31]
After about two (feels like more honestly) weeks of debugging my personal mod pack I have discovered that SoL is causing a crash when the game loads up due to having the food log on your hotbar. If you remove the log (editing player data/clearing inventory/new world) the game will load up and function normally.

This ONLY happens when connecting to a server. Single player functions without issues as far as I can tell.

-- Head --
Stacktrace:
at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:215)
at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:402)

-- Item being rendered --
Details:
Item Type: null
Item Aux: ~~ERROR~~ NullPointerException: null
Item NBT: null
Item Foil: ~~ERROR~~ NullPointerException: null
Stacktrace:
at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
at net.minecraft.client.gui.GuiIngame.func_73832_a(GuiIngame.java:955)
at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:206)
at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:141)

http://paste.ee/p/U1Nkw Complete crash report.

I cannot say with any certainty that it is indeed SoL's fault but I can reproduce this issue.

My current solution is to remove the logs recipe via minetweaker3 and also disable its generation via the config.

Edit: Here is my config just in case. http://paste.ee/p/wvQM1
Edit included info I should of had in the first place, derp.

**Comment by squeek502** [comment]
This will be fixed in the next version. See: 4ed3af3cbb36da3823c241ef68a79d1982826b73
