### ISSUE TITLE
Server crashes and FoodContainer

### ISSUE THREAD

**Issue by BakermanLP** [squeek502/SpiceOfLife#41]
We have got two server crashes that seem to be related to FoodContainer. We are using the latest versions so far. All versions and configs can be found here: https://github.com/BakermanLP/ModpackProjectRETv7

Server runs on cauldron and forge 1207.

First one, a player tried here to add "Beef Wellington" to the food container:
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 10/7/14 4:54 PM
Description: Exception in server tick loop

java.lang.AbstractMethodError: squeek.spiceoflife.items.ItemFoodContainer.getFoodValues(Lnet/minecraft/item/ItemStack;)Lsqueek/applecore/api/food/FoodValues;
at squeek.applecore.api_impl.AppleCoreAccessorMutatorImpl.getUnmodifiedFoodValues(AppleCoreAccessorMutatorImpl.java:56)
at squeek.applecore.api_impl.AppleCoreAccessorMutatorImpl.isFood(AppleCoreAccessorMutatorImpl.java:39)
at squeek.spiceoflife.helpers.FoodHelper.isFood(FoodHelper.java:24)
at squeek.spiceoflife.items.ItemFoodContainer.isItemValidForSlot(ItemFoodContainer.java:375)
at squeek.spiceoflife.inventory.NBTInventory.func_94041_b(NBTInventory.java:189)
at squeek.spiceoflife.inventory.SlotFiltered.func_75214_a(SlotFiltered.java:17)
at squeek.spiceoflife.inventory.ContainerGeneric.func_75135_a(ContainerGeneric.java:231)
at squeek.spiceoflife.inventory.ContainerGeneric.func_82846_b(ContainerGeneric.java:128)
at net.minecraft.inventory.Container.func_75144_a(Container.java:362)
at squeek.spiceoflife.inventory.ContainerGeneric.func_75144_a(ContainerGeneric.java:261)
at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2040)
at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32)
at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
at java.lang.Thread.run(Unknown Source)

Here is the second one:

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 10/7/14 4:54 PM
Description: Exception in server tick loop

java.lang.AbstractMethodError: squeek.spiceoflife.items.ItemFoodContainer.getFoodValues(Lnet/minecraft/item/ItemStack;)Lsqueek/applecore/api/food/FoodValues;
at squeek.applecore.api_impl.AppleCoreAccessorMutatorImpl.getUnmodifiedFoodValues(AppleCoreAccessorMutatorImpl.java:56)
at squeek.applecore.api_impl.AppleCoreAccessorMutatorImpl.isFood(AppleCoreAccessorMutatorImpl.java:39)
at squeek.spiceoflife.helpers.FoodHelper.isFood(FoodHelper.java:24)
at squeek.spiceoflife.items.ItemFoodContainer.isItemValidForSlot(ItemFoodContainer.java:375)
at squeek.spiceoflife.inventory.NBTInventory.func_94041_b(NBTInventory.java:189)
at squeek.spiceoflife.inventory.SlotFiltered.func_75214_a(SlotFiltered.java:17)
at squeek.spiceoflife.inventory.ContainerGeneric.func_75135_a(ContainerGeneric.java:231)
at squeek.spiceoflife.inventory.ContainerGeneric.func_82846_b(ContainerGeneric.java:128)
at net.minecraft.inventory.Container.func_75144_a(Container.java:362)
at squeek.spiceoflife.inventory.ContainerGeneric.func_75144_a(ContainerGeneric.java:261)
at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2040)
at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32)
at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
at java.lang.Thread.run(Unknown Source)

**Comment by squeek502** [comment]
I honestly have no idea how this is possible or what I can do about it. From the [Java documentation about the error](http://docs.oracle.com/javase/7/docs/api/java/lang/AbstractMethodError.html):

> Thrown when an application tries to call an abstract method. Normally, this error is caught by the compiler; this error can only occur at run time if the definition of some class has incompatibly changed since the currently executing method was last compiled.

I guess try redownloading The Spice of Life to make sure your jar isn't corrupted somehow.

**Comment by squeek502** [comment]
Ohhhh... wait, I know what's happening. I'll fix it soon.

**Comment by squeek502** [comment]
Fixed by https://github.com/squeek502/SpiceOfLife/commit/811c9d8fa7b97af47e604b3b0080e3668d97b050
