### ISSUE TITLE
Newer (1.7.2) NEI lag

### ISSUE THREAD

**Issue by Peach774** [squeek502/SpiceOfLife#6]
with your mod installed NEI lags and the console spits:
java.lang.ArrayIndexOutOfBoundsException: 2
at squeek.spiceoflife.proxy.ProxyTiC.getSpecialFoodValues(ProxyTiC.java:46)
at squeek.spiceoflife.foodtracker.FoodValues.get(FoodValues.java:55)
at squeek.spiceoflife.gui.TooltipHandler.onItemTooltip(TooltipHandler.java:48)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_592_TooltipHandler_onItemTooltip_ItemTooltipEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122)
at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:129)
at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:617)
at codechicken.nei.guihook.GuiContainerManager.itemDisplayNameMultiline(GuiContainerManager.java:132)
at codechicken.nei.guihook.GuiContainerManager.concatenatedDisplayName(GuiContainerManager.java:175)
at codechicken.nei.api.ItemInfo.getSearchName(ItemInfo.java:496)
at codechicken.nei.ItemList$PatternItemFilter.matches(ItemList.java:71)
at codechicken.nei.ItemList.itemMatches(ItemList.java:82)
at codechicken.nei.ItemList$ThreadFilterItems.run(ItemList.java:195)

**Comment by squeek502** [comment]
Which version of TiC?

**Comment by Peach774** [comment]
no, that doesnt work on 1.7.2

**Comment by squeek502** [comment]
Sorry, my brain doesn't work. Meant to ask which version of TiC you're using.

**Comment by squeek502** [comment]
Looks like this is actually a bug on TiC's side that would actually cause a crash if you ate the food causing the error (bacon gotten from pig iron tools). I will make sure to stop the console from getting spammed, though.

**Comment by squeek502** [comment]
Also note that the 1.7.2 version of Tinkers Construct is officially unsupported and downloads of it have been pulled by the TiC devs, so any bugs in the 1.7.2 version of Tinkers Construct will not be fixed.
