### ISSUE TITLE
[1.9.4] Crash when combined with Tinkers Construct

### ISSUE THREAD

**Issue by Syndaryl** [squeek502/SpiceOfLife#92]
Forge version 12.17.0.1968

Tinker's is up at https://github.com/SlimeKnights/TinkersConstruct
I'm posting the issue here because I think this _probably_ can be simply handled by wrapping the attempted cast with a try-catch?

java.lang.ClassCastException: slimeknights.tconstruct.library.capability.TinkerPiggybackHandler cannot be cast to squeek.spiceoflife.foodtracker.FoodHistory
    at squeek.spiceoflife.foodtracker.FoodHistory.get(FoodHistory.java:245)
    at squeek.spiceoflife.foodtracker.FoodTracker.onPlayerLogin(FoodTracker.java:87)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_187_FoodTracker_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:558)
    at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:228)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:240)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:53)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:189)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:730)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
    at java.lang.Thread.run(Unknown Source)

**Comment by squeek502** [comment]
Should be fixed in The Spice of Life v1.3.3, see #91

**Comment by squeek502** [comment]
Closing this as fixed. Please re-open if you're still getting the error.
